spring:
  datasource:
    url: jdbc:mysql://localhost:3306/osahaneat
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB

jwt:
  privateKey: W5ta9hd9VawIHTRqs23bEcg1JiUC22KeGPELVeTrago=

fileUpload:
  rootPath: D:\Intellij\uploads



